services:
  tron-project:
    image: tron-project:latest
    build:
      context: .
      dockerfile: dockerfile
    container_name: tron-project
    restart: unless-stopped
    ports:
      - "9898:9898"
      - "27017:27017"
    environment:
      - NODE_ENV=production
      - PORT=9898
      - MONGO_URI=mongodb://localhost:27017/tron